# Unified SD3-style Configuration: MMDiT with Flow Matching
# ~1.7M parameters with CFG support
# Represents the Stable Diffusion 3 / Flux approach

exp_name: "unified_sd3_mmdit_flow"
exp_dir: "./experiments/unified_sd3_mmdit_flow"
use_wandb: false
device: "cuda"
use_torch_compile: false  # MMDiT may have compile issues

# Model configuration (~1.7M params)
model:
  architecture: "mmdit"
  in_channels: 1
  out_channels: 1
  embed_dim: 96         # img_dim
  text_dim: 96          # txt_dim (symmetric)
  depth: 3              # 3 transformer blocks
  patch_size: 2
  use_latents: false
  use_conditioning: true

# Data configuration
data:
  mnist_root: "./data/mnist"
  image_size: 32
  num_workers: 4

# Training configuration with CFG
training:
  target: "flow"        # Flow matching (SD3/Flux style)
  epochs: 100           # More epochs for better quality
  batch_size: 256       # Optimized for RTX 4060 GPU
  lr: 0.00014          # Scaled with batch size (sqrt scaling)
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01    # Light weight decay
  grad_clip: 1.0
  use_scheduler: true
  cfg_dropout_prob: 0.1 # 10% CFG dropout for training

# Sampling configuration
sampling:
  steps: 50             # Flow matching is efficient, 50 is enough
  sample_freq: 5
  num_samples: 64
  cfg_scale: 3.0        # Lower CFG scale for flow matching on MNIST

# Logging configuration
logging:
  log_freq: 100
  checkpoint_freq: 10